"""Drop UNIQUE(student_id) on consents and add an index.

Consent records are immutable; revocation and re-acceptance create new rows
for the same student (see ConsentRepository.register_consent and tests in
tests/property/test_consent_immutability.py). The original schema kept a
UNIQUE constraint on student_id which prevented inserting a second record
for the same student, causing 500 errors when a student re-accepted terms
after the seed already wrote a consent row for them.

Revision ID: 0022
Revises: 0021
Create Date: 2026-05-14
"""

from alembic import op

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop the implicit unique constraint generated by the initial schema.
    op.execute("ALTER TABLE consents DROP CONSTRAINT IF EXISTS consents_student_id_key")
    # Replace it with a plain (non-unique) index for query performance on get_consent().
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_consents_student_id ON consents (student_id)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_consents_student_id")
    # Recreating the unique constraint would fail if duplicate student_id rows exist;
    # callers must dedupe consents before running this downgrade.
    op.execute(
        "ALTER TABLE consents ADD CONSTRAINT consents_student_id_key UNIQUE (student_id)"
    )
